name: Деплой сборника мест от cdROma в Сербии

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Сборка и публикация на Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода из репозитория
        uses: actions/checkout@v3

      - name: Настройка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Установка зависимостей
        run: npm ci

      - name: Генерация Prisma клиента
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Сборка проекта
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NODE_ENV: "production"

      - name: Публикация на Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: '.'
          vercel-args: "--prod"
